- name: "Kernel Parameter 설정: /etc/sysctl.conf"
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    insertafter: 'EOF'
    line: '{{ item }}'
  with_items:
    - 'net.core.default_qdisc=fq'
    - 'net.ipv4.tcp_congestion_control=bbr'
    - 'net.core.somaxconn = 65535'
    - 'net.ipv4.tcp_max_syn_backlog = 30000'
    - 'net.ipv4.tcp_syncookies = 1'
    - 'net.core.netdev_max_backlog = 5000'
    - 'fs.inotify.max_user_watches=524288'
    - 'net.core.netdev_max_backlog=30000'
    - 'net.ipv4.tcp_max_tw_buckets=1800000'
    - 'net.core.wmem_default=253952'
    - 'net.core.rmem_default=253952'
    - 'net.core.wmem_max=8388608'
    - 'net.core.rmem_max=8388608'
    - 'net.ipv4.tcp_wmem=8192   87380   8388608'
    - 'net.ipv4.tcp_rmem=8192   87380   8388608'

- name: "Kernel Parameter 적용: /etc/sysctl.conf"
  shell: |
    sysctl -p /etc/sysctl.conf
  ignore_errors: true

- name: "apt-get update" 
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes