---
- hosts: all
  vars:
    - default_user: 'ansible'
    - default_password: 'P@ssw0rd'
  gather_facts: no
  become: true

  tasks:
  - name: Add user name ansible
    user:
      name: "{{ default_user }}"
      password: "{{ default_password | password_hash('sha512') }}"
      generate_ssh_key: yes
      state: present

  - name: Add ansible user to sudoers
    copy: 
      dest: "/etc/sudoers.d/{{ default_user }}"
      content: "{{ default_user }} ALL=(ALL) NOPASSWD: ALL"

  - name: Deploy SSH KEY
    authorized_key:
      user: "{{ default_user }}"
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      state: present
      