---
- hosts: all
#  vars:
#    - SRC_DIR: /fslog/dev
#    - DST_DIR: /fslog
#    - TARGET_HOST: ta-test01

  tasks:
    - name: "Archive Source dir only directory"
      shell: |
        cd "{{ SRC_DIR }}"
        rm -f /tmp/$(pwd |awk -F/ '{print $NF}').tar
        echo "find . -type d|xargs tar rfv /tmp/$(pwd |awk -F/ '{print $NF}').tar --no-recursion"|sh -x
      ignore_errors: yes

    - name: "File Name register"
      shell: |
        cd "{{ SRC_DIR }}"
        echo "$(pwd |awk -F/ '{print $NF}').tar"
      register: SRC_FILE_NAME

    - name: "Copy to local "
      shell: |
        scp auditor@"{{ ansible_hostname }}":/tmp/{{ SRC_FILE_NAME.stdout }} /mnt/d/tmp
      run_once: yes
      delegate_to: localhost
#      remote_user: root
#      become: no

    - name: "Delete Remote Archive File"
      file:
        path: /tmp/{{ SRC_FILE_NAME.stdout }}
        state: absent

    - name: "Make Target Directory"
      file: 
        path: "{{ DST_DIR }}"
        state: directory
        recurse: yes
        owner: root
        group: root
      delegate_to: '{{ item }}'
      with_items: "{{ TARGET_HOST.split('\n') }}"

    - name: "Unarchive Source dir"
      unarchive: 
        src: /mnt/d/tmp/{{ SRC_FILE_NAME.stdout }}
        dest: "{{ DST_DIR }}"
      delegate_to: '{{ item }}'
      with_items: "{{ TARGET_HOST.split('\n') }}"

    - name: "Delete local Files"
      shell: |
        rm -f /mnt/d/tmp/{{ SRC_FILE_NAME.stdout }}
      run_once: yes
      delegate_to: localhost
#      become: no