---
- hosts: all
  tasks:
    - name: "password change date"
      shell: |
            cat /dev/null > /tmp/chage_list_before.txt
            cat /dev/null > /tmp/chage_list_after.txt

            for i in `cat /etc/passwd |egrep -e "[4-9][0-9][0-9][0-9]|root|auditor"|grep -v nologin|awk -F: '{ print $1 }'`
            do
            echo "========[ $i ] ========" >> /tmp/chage_list_before.txt
            chage -l $i 1>> /tmp/chage_list_before.txt
            done

            for i in `cat /etc/passwd |egrep -e "[4-9][0-9][0-9][0-9]|root|auditor"|grep -v nologin|awk -F: '{ print $1 }'`
            do
            echo "========[ $i ] ========"
            chage -d `date "+%Y-%m-%d"` $i
            done

            for i in `cat /etc/passwd |egrep -e "[4-9][0-9][0-9][0-9]|root|auditor"|grep -v nologin|awk -F: '{ print $1 }'`
            do
            echo "========[ $i ] ========" >> /tmp/chage_list_after.txt
            chage -l $i 1>> /tmp/chage_list_after.txt
            done